controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix:
      en: '/en'
      zh_CN: ''
index:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    #route: 'easyadmin'
    path: '/admin'
    version: 'current'
    permanent: true
    keepQueryParams: true
    keepRequestMethod: true
